const num = 100
// console.log(num)

//other ways of dedicately define number variales is

const num_1 = new Number(300)
// console.log(num_1);              //shows the output as [number:300]

// console.log(num_1.toString().length) // this shows 3 in the result

// console.log(num_1.toFixed(2)) // this gives output  op: 300.00

let num3 = 100.547
// console.log(num3.toPrecision(3)) // for precision output is 101

const hundreds = 100000
// console.log(hundreds.toLocaleString())  // gives the output in english number system comma after every 3 digits
// console.log(hundreds.toLocaleString('en-In'))  // gives output in our number system

// for random values 
console.log(Math.random() *10); // javascript returns the random values range (0-1)

// for the values from desired range is generated by
let minvalue = 13
let maxvalue = 27
console.log(Math.floor(Math.random()*(maxvalue - minvalue + 1)) + minvalue); // we added 1 because sometimes the value returned 
                                                                            // may be zero so to make it non zero

